version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: aiqer/goliveirarep:bookmanager2
    ports:
      - "5000:5000"
    networks:
      - webnet
networks:
  webnet:

